export {Footer} from './footer'
export {Header} from './header'
export {Main} from './main'
export {MobMenu} from './mob-menu'
export {Section1} from './section-1'
export {Section2} from './section-2'
export {Section3} from './section-3'
export {Section5} from './section-5'
export {Section6} from './section-6'
export {Section7} from './section-7'
export {Landing} from './landing'
export {LangMenu} from './lang-menu'
export {Line1, Line2, Line3, Line4, Line5} from './lines'
export {Ellipse1, Ellipse2} from './ellipses'
export {Arrow} from './arrow'
export {Arc} from './arc'
